// Evidence store for the report: every capture is written to evidence/<phase>/ and listed in
// evidence/manifest.json, from which evidence/README.md (the index) is regenerated.
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

export const EVIDENCE_DIR = fileURLToPath(new URL("../../evidence/", import.meta.url));
const MANIFEST = join(EVIDENCE_DIR, "manifest.json");

export interface EvidenceMeta {
  /** Folder under evidence/, e.g. "01-foundation". */
  phase: string;
  /** File name without extension, e.g. "replica-set-status". */
  name: string;
  title: string;
  /** What this proves, in one or two sentences. */
  shows: string;
  /** Report section it supports, e.g. "7. Characteristics: replication". */
  reportSection?: string;
}

interface ManifestEntry extends EvidenceMeta {
  file: string;
  capturedAt: string;
}

function loadManifest(): ManifestEntry[] {
  return existsSync(MANIFEST) ? JSON.parse(readFileSync(MANIFEST, "utf8")) : [];
}

function register(meta: EvidenceMeta, file: string) {
  const entries = loadManifest().filter((e) => e.file !== file);
  entries.push({ ...meta, file, capturedAt: new Date().toISOString() });
  entries.sort((a, b) => a.file.localeCompare(b.file));
  writeFileSync(MANIFEST, JSON.stringify(entries, null, 2) + "\n");
  writeIndex(entries);
  console.log(`  ✓ evidence/${file}`);
}

/** Save text output (command output, JSON, explain plans...) as a Markdown evidence file. */
export function recordText(meta: EvidenceMeta, opts: { body: string; command?: string; lang?: string }) {
  const file = `${meta.phase}/${meta.name}.md`;
  const path = join(EVIDENCE_DIR, file);
  mkdirSync(dirname(path), { recursive: true });
  const lines = [
    `# ${meta.title}`,
    "",
    `- **Captured:** ${new Date().toISOString()}`,
    `- **Shows:** ${meta.shows}`,
    ...(meta.reportSection ? [`- **Report section:** ${meta.reportSection}`] : []),
    ...(opts.command ? [`- **Command:** \`${opts.command}\``] : []),
    "",
    "```" + (opts.lang ?? "text"),
    opts.body.trimEnd(),
    "```",
    "",
  ];
  writeFileSync(path, lines.join("\n"));
  register(meta, file);
}

/** Register an image that has already been written to evidence/<phase>/<name>.png. */
export function recordImage(meta: EvidenceMeta) {
  register(meta, `${meta.phase}/${meta.name}.png`);
}

export function imagePath(meta: Pick<EvidenceMeta, "phase" | "name">) {
  const path = join(EVIDENCE_DIR, meta.phase, `${meta.name}.png`);
  mkdirSync(dirname(path), { recursive: true });
  return path;
}

function writeIndex(entries: ManifestEntry[]) {
  const byPhase = new Map<string, ManifestEntry[]>();
  for (const e of entries) byPhase.set(e.phase, [...(byPhase.get(e.phase) ?? []), e]);

  const out = [
    "# Evidence",
    "",
    "Screenshots, command output and measurements captured for the report.",
    "**Generated by `npm run evidence`. Do not edit by hand.** Re-run a capture to refresh it.",
    "",
  ];
  for (const [phase, list] of byPhase) {
    out.push(`## ${phase}`, "", "| Evidence | Shows | Report section | Captured |", "|---|---|---|---|");
    for (const e of list) {
      out.push(`| [${e.title}](${e.file}) | ${e.shows} | ${e.reportSection ?? ""} | ${e.capturedAt.slice(0, 16).replace("T", " ")} |`);
    }
    out.push("");
  }
  writeFileSync(join(EVIDENCE_DIR, "README.md"), out.join("\n"));
}

export const repoRoot = fileURLToPath(new URL("../../", import.meta.url));
export const rel = (p: string) => relative(repoRoot, p);
