import { MongoClient, type Db } from "mongodb";
import { config, connectMongo } from "@da2/shared/server";
import { recordText } from "../lib";
import type { EvidenceSet } from "./index";

const phase = "06-simulator";
const TZ = "Asia/Colombo";

const median = (xs: number[]) => [...xs].sort((a, b) => a - b)[Math.floor(xs.length / 2)];
async function timed<T>(fn: () => Promise<T>, runs = 5): Promise<{ result: T; ms: number }> {
  const times: number[] = [];
  let result!: T;
  for (let i = 0; i < runs; i++) {
    const t = performance.now();
    result = await fn();
    times.push(performance.now() - t);
  }
  return { result, ms: Math.round(median(times)) };
}
const mb = (bytes: number) => `${(bytes / 1024 / 1024).toFixed(2)} MB`;

export const simulator: EvidenceSet = {
  description: "Simulated dataset: daily volume, funnel/device/search breakdowns, raw-aggregation baseline, time-series storage vs regular collection",
  async run() {
    const db = (await connectMongo()).db as unknown as Db;
    const events = db.collection("events");

    // 1. Dataset overview, per local (Sri Lanka) day
    const perDay = await events
      .aggregate([
        { $group: { _id: { day: { $dateToString: { date: "$ts", format: "%Y-%m-%d", timezone: TZ } } }, events: { $sum: 1 }, sessions: { $addToSet: "$meta.sessionId" }, orders: { $sum: { $cond: [{ $eq: ["$type", "order_placed"] }, 1, 0] } } } },
        { $project: { _id: 0, day: "$_id.day", events: 1, sessions: { $size: "$sessions" }, orders: 1 } },
        { $sort: { day: 1 } },
      ])
      .toArray();
    const totals = perDay.reduce((t, d) => ({ events: t.events + d.events, sessions: t.sessions + d.sessions, orders: t.orders + d.orders }), { events: 0, sessions: 0, orders: 0 });
    const users = await db.collection("users").countDocuments({ email: /^sim-\d+@cellora\.test$/ });
    const orders = await db.collection("orders").countDocuments();
    recordText(
      {
        phase,
        name: "dataset-overview",
        title: "Simulated dataset: daily volume",
        shows: `${totals.sessions.toLocaleString()} sessions and ${totals.events.toLocaleString()} events over ${perDay.length} days, generated by the traffic simulator and ingested through the real pipeline (Redis Stream -> worker). Weekend uplift and a promotion day (1.8x traffic) are visible.`,
        reportSection: "11. Evaluation: test data",
      },
      {
        command: "npm run sim:backfill -- --days 14 --per-day 900   then   db.events.aggregate([$group by local day])",
        body: [
          "day          sessions   events  orders  conversion",
          ...perDay.map((d) => `${d.day}   ${String(d.sessions).padStart(7)}  ${String(d.events).padStart(7)}  ${String(d.orders).padStart(6)}  ${((d.orders / d.sessions) * 100).toFixed(1).padStart(8)}%`),
          "",
          `total        ${String(totals.sessions).padStart(7)}  ${String(totals.events).padStart(7)}  ${String(totals.orders).padStart(6)}  ${((totals.orders / totals.sessions) * 100).toFixed(1).padStart(8)}%`,
          `simulated customer accounts: ${users}   orders in the orders collection: ${orders}`,
        ].join("\n"),
      },
    );

    // 2. Behaviour breakdowns: event mix, device mix, searches (incl. zero-result)
    const byType = await events.aggregate([{ $group: { _id: "$type", n: { $sum: 1 } } }, { $sort: { n: -1 } }]).toArray();
    const byDevice = await events
      .aggregate([{ $match: { source: "client" } }, { $group: { _id: "$meta.sessionId", device: { $first: "$device.type" } } }, { $group: { _id: "$device", sessions: { $sum: 1 } } }, { $sort: { sessions: -1 } }])
      .toArray();
    const searches = await events
      .aggregate([{ $match: { type: "search" } }, { $group: { _id: "$props.query", n: { $sum: 1 }, results: { $first: "$props.resultCount" } } }, { $sort: { n: -1 } }, { $limit: 12 }])
      .toArray();
    const zeroResults = await events
      .aggregate([{ $match: { type: "search", "props.resultCount": 0 } }, { $group: { _id: "$props.query", n: { $sum: 1 } } }, { $sort: { n: -1 } }])
      .toArray();
    const deviceTotal = byDevice.reduce((s, d) => s + d.sessions, 0);
    recordText(
      { phase, name: "behaviour-breakdowns", title: "Event, device and search breakdowns", shows: "The mix of event types, the device split (mobile-first), top searches, and zero-result searches (a catalog-gap signal). Also shows a limitation of $text search: term-OR matching.", reportSection: "8. Applications: behavioural analytics / 10. Limitations: text search" },
      {
        command: "db.events.aggregate([$group by type / by session device / by search query])",
        body: [
          "events by type:",
          ...byType.map((t) => `  ${t._id.padEnd(18)} ${String(t.n).padStart(7)}`),
          "",
          "sessions by device:",
          ...byDevice.map((d) => `  ${String(d._id).padEnd(10)} ${String(d.sessions).padStart(6)}  (${((d.sessions / deviceTotal) * 100).toFixed(0)}%)`),
          "",
          "top searches (query, times searched, results):",
          ...searches.map((s) => `  ${String(s._id).padEnd(26)} ${String(s.n).padStart(5)}   ${s.results}`),
          "",
          "zero-result searches (catalog gaps):",
          ...zeroResults.map((s) => `  ${String(s._id).padEnd(26)} ${String(s.n).padStart(5)}`),
          "",
          'Note: "iphone 17" is not zero-result: $text matches ANY term, so "iphone" alone returns every',
          "iPhone product. MongoDB text indexes have no phrase-level relevance tuning or typo tolerance;",
          "a dedicated search engine (Atlas Search / Elasticsearch) would be needed for that.",
        ].join("\n"),
      },
    );

    // 3. Baseline: a funnel-style aggregation over ALL raw events (Phase 7 rollups will beat this)
    const funnelPipeline = [
      { $match: { type: { $in: ["product_view", "add_to_cart", "checkout_started", "order_placed"] } } },
      { $group: { _id: { s: "$meta.sessionId", t: "$type" } } },
      { $group: { _id: "$_id.t", sessions: { $sum: 1 } } },
    ];
    const { result: steps, ms: rawMs } = await timed(() => events.aggregate(funnelPipeline).toArray());
    const count = Object.fromEntries(steps.map((s) => [s._id, s.sessions]));
    const order = ["product_view", "add_to_cart", "checkout_started", "order_placed"];
    recordText(
      {
        phase,
        name: "raw-aggregation-baseline",
        title: "Baseline: funnel counts computed from raw events",
        shows: `Sessions reaching each funnel step, computed by scanning every raw event: median ${rawMs} ms over 5 runs on ${totals.events.toLocaleString()} events. This is the baseline the Phase 7 rollups and Redis cache are compared against.`,
        reportSection: "9. Strengths / 11. Evaluation: performance",
      },
      {
        command: "db.events.aggregate([$match funnel types, $group by session+type, $group by type])  (median of 5 runs)",
        body: [
          ...order.map((k, i) => `${k.padEnd(18)} ${String(count[k] ?? 0).padStart(6)} sessions${i ? `   (${(((count[k] ?? 0) / (count[order[i - 1]] || 1)) * 100).toFixed(1)}% of previous step)` : ""}`),
          "",
          `overall: ${(((count.order_placed ?? 0) / (count.product_view || 1)) * 100).toFixed(2)}% of sessions that viewed a product placed an order`,
          `median query time: ${rawMs} ms (full scan of ${totals.events.toLocaleString()} events; grows linearly with data)`,
        ].join("\n"),
      },
    );

    // 4. Time-series storage vs the same data in a regular collection
    // Copy events into a temporary regular collection, force a checkpoint (as root) so on-disk
    // sizes are accurate, compare, then drop the copy.
    const tmp = "events_regular_tmp";
    await db.collection(tmp).drop().catch(() => {});
    await events.aggregate([{ $project: { _id: 0 } }, { $out: tmp }]).toArray();
    const root = await MongoClient.connect(config.mongoUri.replace(/\/\/[^@]+@/, `//${process.env.MONGO_ROOT_USER}:${process.env.MONGO_ROOT_PASSWORD}@`));
    await root.db("admin").command({ fsync: 1 });
    await root.close();
    const stats = async (name: string) => (await db.collection(name).aggregate([{ $collStats: { storageStats: {} } }]).toArray())[0].storageStats;
    const ts = await stats("events");
    const plain = await stats(tmp);
    await db.collection(tmp).drop();
    const tsInfo = ts.timeseries ?? {};
    const bucketCount = tsInfo.bucketCount ?? 0;
    recordText(
      {
        phase,
        name: "timeseries-storage",
        title: "Time-series collection vs regular collection storage",
        shows: `The same ${totals.events.toLocaleString()} events stored as a time-series collection (grouped into ${bucketCount.toLocaleString()} compressed buckets) and as a regular collection. Buckets average ${(totals.events / (bucketCount || 1)).toFixed(1)} events: small, because sessionId in the metaField gives each session its own buckets (the trade-off documented in data-model §4.4).`,
        reportSection: "7. Characteristics: time-series collections / 10. Limitations: metaField cardinality",
      },
      {
        command: "$collStats storageStats on events vs a $out copy into a regular collection (after fsync)",
        body: [
          "                               time-series     regular collection",
          `documents stored               ${String(bucketCount).padStart(10)} buckets  ${String(plain.count).padStart(10)} documents`,
          `data size (uncompressed BSON)  ${mb(ts.size).padStart(15)}  ${mb(plain.size).padStart(15)}`,
          `storage size on disk           ${mb(ts.storageSize).padStart(15)}  ${mb(plain.storageSize).padStart(15)}`,
          `index size                     ${mb(ts.totalIndexSize).padStart(15)}  ${mb(plain.totalIndexSize).padStart(15)}   (regular copy: _id index only)`,
          "",
          `events per bucket (average):   ${(totals.events / (bucketCount || 1)).toFixed(1)}`,
          `bucket stats: ${JSON.stringify({ avgBucketSize: tsInfo.avgBucketSize, numBucketInserts: tsInfo.numBucketInserts, numBucketsClosedDueToCount: tsInfo.numBucketsClosedDueToCount, numBucketsClosedDueToTimeForward: tsInfo.numBucketsClosedDueToTimeForward, numBucketsArchivedDueToMemoryThreshold: tsInfo.numBucketsArchivedDueToMemoryThreshold })}`,
        ].join("\n"),
      },
    );
  },
};
